-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.products
(
    id serial,
    name character varying(50),
    producer character varying(50),
    count integer DEFAULT 0,
    price integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.history_of_price
(
    id serial,
    name character varying(50),
    price integer,
    date timestamp without time zone,
    PRIMARY KEY (id)
);
END;