-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.airports
(
    id serial,
    name character varying(50),
    city character varying(100),
    country character varying(100),
    iata_code character varying(3),
    icao_code character varying(4),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.planes
(
    id serial,
    registration_number character varying(20),
    model character varying(50),
    manufacturer character varying(100),
    max_speed integer,
    range integer,
    capacity integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.flight_schedule
(
    id serial,
    plane_id integer,
    departure_airport_id integer,
    departure_time timestamp without time zone,
    arrival_airport_id integer,
    arrival_time timestamp without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.flight_schedule
    ADD FOREIGN KEY (plane_id)
    REFERENCES public.planes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flight_schedule
    ADD FOREIGN KEY (departure_airport_id)
    REFERENCES public.airports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flight_schedule
    ADD FOREIGN KEY (arrival_airport_id)
    REFERENCES public.airports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;